api_version = "2026-04"

[[extensions]]
name = "bundle-discount"
handle = "bundle-discount"
uid = "208e9edf-8b9b-6b74-3f3a-539fdede2328f859a084"
type = "function"
description = "Bundle Engine: quantity breaks, BOGO, free gifts, mix & match"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
  watch = [ "src/**/*.js" ]